version: '3.2'

services:
    vote:
        depends_on:
            - redis

    main_web:
        depends_on: 
            - psql
        
    redis:
        image: redis
    
    psql:
        image: postgres:12.2
        volumes:
            - psql_data:/var/lib/postgresql/data
            - ./psql/client_db_init.sh:/docker-entrypoint-initdb.d/db_init.sh

    worker:
        build: ./worker/.
        depends_on: 
            - redis
            - psql

    nginx:
        ports:
            - 80:80
        depends_on: 
            - vote
        

volumes:
    psql_data:
